Survey.Web/Controllers/AnswersAdminController.cs
using System.Web.Mvc;

namespace Survey.Web.Controllers
{
    public class AnswersAdminController : SurveyControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Survey.Web/Controllers/QuestionAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Survey.Web.Controllers
{
    public class QuestionAdminController : SurveyControllerBase
    {
        // GET: QuestionAdmin
        public ActionResult Index()
        {
            return View();
        }
    }
}

Survey.Web/Controllers/SurveyAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Survey.Application.SurveyService;
using Survey.Application.SurveyService.Dto;

namespace Survey.Web.Controllers
{
    public class SurveyAdminController : SurveyControllerBase
    {
        private readonly ISurveyAppService _surveyAppService;

        public SurveyAdminController(ISurveyAppService surveyAppService)
        {
            _surveyAppService = surveyAppService;
        }

        // GET: SurveyAdmin
        public async Task<ActionResult> Index()
        {
            var surveys = await _surveyAppService.GetSurveys();
            return View(surveys);
        }

        public async Task<ActionResult> AddQuestions(int id)
        {
            var availableQuestions = _surveyAppService.GetAvailableQuestions(id);
            List<QuestionDto> questions = _surveyAppService.GetAssignedQuestions(id);
            var survey = await _surveyAppService.GetSurveyById(id);

            return View(new SetQuestionsDto(availableQuestions, questions, survey));
        }
    }
}

Survey.Web/Controllers/SurveyController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Survey.Application.SurveyService;

namespace Survey.Web.Controllers
{
    public class SurveyController : SurveyControllerBase
    {
        // GET: Survey
        private readonly ISurveyAppService _surveyAppService;

        public SurveyController(ISurveyAppService surveyAppService)
        {
            _surveyAppService = surveyAppService;
        }
        public async Task<ActionResult> Index()
        {
            var surveys = await _surveyAppService.GetSurveys();
            return View(surveys);
        }

        public async Task<ActionResult> LoadSurvey(string surveyurl)
        {
            var survey = await _surveyAppService.GetSurveyFirstQuestion(surveyurl);
            return View(survey);
        }

        public ActionResult GetNextQuestion(int questionId, int surveyId)
        {
            var question = _surveyAppService.GetQuestion(surveyId, questionId);
            return View(question);
        }
    }
}

Survey.Web/Views/AnswersAdmin/Index.cshtml
@model dynamic

@{
    Layout = "~/Views/Shared/_Layout_Survey.cshtml";
}

<h2>title</h2>

Survey.Web/Views/QuestionAdmin/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Survey.cshtml";
}

<h2>title</h2>

Survey.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="~/favicon.ico">
    <title>LittleSurvey</title>

</head>
<body>
<div class="container">
    @RenderBody()
</div>

@Scripts.Render("~/Bundles/vendor/js/bottom")
@Scripts.Render("~/Bundles/js")

<script>
    //Localizing momentjs
    moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
</script>

<!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
<script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
<script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

<!-- SignalR scripts -->
<script src="~/signalr/hubs"></script>
@Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

<!-- View specific scripts -->
@RenderSection("scripts", required: false)
</body>
</html>

Survey.Web/Views/Shared/_Layout_Survey.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="~/favicon.ico">
    <title>Survey</title>

    <link href="/Content/themes/base/all.css" rel="stylesheet" />
    <link href="/Content/bootstrap-cosmo.min.css" rel="stylesheet" />
    <link href="/Content/toastr.min.css" rel="stylesheet" />
    <link href="/Scripts/sweetalert/sweet-alert.css" rel="stylesheet" />
    <link href="/Content/flags/famfamfam-flags.css" rel="stylesheet" />
    <link href="/Content/font-awesome.min.css" rel="stylesheet" />

    <link href="/css/main.css" rel="stylesheet" />

</head>
<body>
    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
    //Localizing momentjs
    moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    <script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

Survey.Web/Views/Survey/GetNextQuestion.cshtml
@model Survey.Application.SurveyService.Dto.QuestionDto

@{
    Layout = null;
}

<form>
    <div class="tab-pane active" role="tabpanel" id="step_@Model.Id">
        <h3>@Model.QuestionText</h3>
        @Html.Hidden("QuestionId", Model.Id)
        @if (Model.QuestionType == 0)
        {

            foreach (var r in Model.OfferedAnswers)
            {
                <div class="radio">
                    <label>
                        @if (Model.OfferedAnswerIds.Any(a => a == r.Id))
                        {
                            <input required="" type="radio" checked="checked" name="Question" value="@r.Id"/>@r.AnswerText
                        }
                        else
                        {

                            <input type="radio" required="" name="Question" value="@r.Id"/>
                            @r.AnswerText
                        }
                    </label>
                </div>
            }

        }
        @if (!Model.OfferedAnswers.Any())
        {
            <input type="text" class="OtherText form-control" required="" name="Question" value="@Model.OtherText" />
        }
        <ul class="list-inline pull-right">
            @if (Model.PrevQuestion > 0)
            {
                <li><button type="button" class="btn btn-primary prev-step" data-survey="@Model.SurveyId" data-next="@Model.PrevQuestion">Anterior</button></li>

            }
            @if (Model.NextQuestion > 0)
            {
                <li><button type="submit" class="btn btn-primary next-step" data-next="@Model.NextQuestion">Guardar y continuar</button></li>

            }
            else
            {
                <li><button type="button" class="btn btn-primary next-step" data-survey="@Model.SurveyId" data-next="@Model.NextQuestion">Guardar y Finalizar</button></li>
            }
        </ul>
    </div>
</form>
            

Survey.Web/Views/Survey/Index.cshtml
@model IEnumerable<Survey.Application.SurveyService.Dto.SurveyDto>

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout_Survey.cshtml";
}

@foreach (var sr in Model)
{
    <li class="list-group-item">
        <a href="@Url.Action("LoadSurvey", new {sr.SurveyUrl})">@sr.Description</a>
                    
    </li>
}

Survey.Web/Views/Survey/LoadSurvey.cshtml
@model Survey.Application.SurveyService.Dto.SurveyWithOnlyFirstQuestionForUserDto

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout_Survey.cshtml";
}

<h2>@Model.Description</h2>
<div class="container">
    <div class="row">
        <div class="col-md-12" id="survey_section">
            <form>
                <div class="tab-pane active" role="tabpanel" id="step_@Model.Answer.Id">
                    <h3>@Model.Answer.QuestionText</h3>

                    @Html.Hidden("QuestionId", Model.Answer.Id)

                    @if (Model.Answer.QuestionType == 0)
                    {

                        foreach (var r in Model.Answer.OfferedAnswers)
                        {
                            <div class="radio">
                                <label>
                                    @if (Model.Answer.OfferedAnswerIds.Any(a => a == r.Id))
                                    {
                                        <input required="" class="js-value" type="radio" checked="checked" name="Question" value="@r.Id" />@r.AnswerText
                                    }
                                    else
                                    {

                                        <input type="radio" class="js-value" required="" name="Question" value="@r.Id" />
                                        @r.AnswerText
                                    }
                                </label>
                            </div>
                        }
                    }
                    @if (!Model.Answer.OfferedAnswers.Any())
                    {
                        <input type="text" class="OtherText form-control" required="" name="Question" value="@Model.Answer.OtherText" />
                    }
                    <ul class="list-inline pull-right">
                        @if (Model.Answer.PrevQuestion > 0)
                        {
                            <li><button type="button" class="btn btn-primary prev-step" data-survey="@Model.Id" data-prev="@Model.Answer.PrevQuestion">Anterior</button></li>

                        }
                        @if (Model.Answer.NextQuestion > 0)
                        {
                            <li><button type="button" class="btn btn-primary next-step" data-survey="@Model.Id" data-next="@Model.Answer.NextQuestion">Guardar y continuar</button></li>

                        }
                        else
                        {
                            <li><button type="button" class="btn btn-primary next-step" data-survey="@Model.Id" data-next="@Model.Answer.NextQuestion">Guardar y Finalizar</button></li>
                        }
                    </ul>
                </div>
            </form>

        </div>
    </div>
</div>


@section Scripts{
  
    <script src="~/Views/Survey/LoadSurvey.js"></script>
}

Survey.Web/Views/Survey/Survey.cshtml
@model Survey.Application.SurveyService.Dto.SurveyWithOnlyFirstQuestionForUserDto

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Description</h2>
<div class="container">
    <div class="row">
        <div class="col-md-12" id="survey_section">
            <form>
                <div class="tab-pane active" role="tabpanel" id="step_@Model.Answer.Id">
                    <h3>@Model.Answer.QuestionText</h3>

                    @Html.Hidden("QuestionId", Model.Answer.Id)

                    @if (Model.Answer.QuestionType == 0)
                    {

                        foreach (var r in Model.Answer.OfferedAnswers)
                        {
                            <div class="radio">
                                <label>
                                    @if (Model.Answer.OfferedAnswerIds.Any(a => a == r.Id))
                                    {
                                        <input required="" class="js-value" type="radio" checked="checked" name="Question" value="@r.Id" />@r.AnswerText
                                    }
                                    else
                                    {

                                        <input type="radio" class="js-value" required="" name="Question" value="@r.Id" />
                                        @r.AnswerText
                                    }
                                </label>
                            </div>
                        }
                    }

                    <ul class="list-inline pull-right">
                        @if (Model.Answer.PrevQuestion > 0)
                        {
                            <li><button type="button" class="btn btn-primary prev-step" data-survey="@Model.Id" data-prev="@Model.Answer.PrevQuestion">Anterior</button></li>

                        }
                        @if (Model.Answer.NextQuestion > 0)
                        {
                            <li><button type="button" class="btn btn-primary next-step" data-survey="@Model.Id" data-next="@Model.Answer.NextQuestion">Guardar y continuar</button></li>

                        }
                        else
                        {
                            <li><button type="button" class="btn btn-primary next-step" data-survey="@Model.Id" data-next="@Model.Answer.NextQuestion">Guardar y Finalizar</button></li>
                        }
                    </ul>
                </div>
            </form>

        </div>
    </div>
</div>


@section Scripts{
    <script>
        $("body").on("click", ".next-step", function () {
            var surveyId = $(this).data("survey");
            var nextId = $(this).data("next");

            var service = abp.services.app.survey;

            service.answerQuestion({
                SurveyId: surveyId,
                QuestionId: $("#QuestionId").val(),
                OfferedAnswerIds: [$("input:radio[name=Question]:checked").val()]
            }).done(function () {
                if (nextId == 0) {
                    window.location.reload();
                } else {
                    $("#survey_section").load("/Home/GetNextQuestion?questionId=" + nextId + "&surveyId=" + surveyId);
                }
                
            });


        });
    </script>
}

Survey.Web/Views/SurveyAdmin/AddQuestions.cshtml
@model Survey.Application.SurveyService.Dto.SetQuestionsDto
@{
    Layout = "~/Views/Shared/_Layout_Survey.cshtml";
}
<h2>@L("AddQuestions") @Model.Survey.Description</h2>
<style>
    .connectedSortable {
        min-height: 300px;
        background-color: whitesmoke;
    }
</style>
@Html.Hidden("SurveyId",Model.Survey.Id)
<div class="row">
    <div class="col-md-6">
        <h4>Disponibles</h4>
        <div id="listOne" class="list-group connectedSortable">

            @foreach (var elm in Model.AvailableQuestions)
            {
                <div class="list-group-item js-question"  data-id="@elm.Id">
                    @elm.QuestionText
                    <p>
                        <a class="btn btn-primary btn-xs js-set-answ" data-id="@elm.Id">Ver respuestas</a>
                    </p>
                </div>
            }

        </div>
    </div>
    <div class="col-md-6">
        <h4>Asignadas</h4>
        <div id="listTwo" class="list-group connectedSortable">

            @foreach (var elm in Model.AssignedQuestions)
            {
                <div class="list-group-item js-question" data-id="@elm.Id">
                    @elm.QuestionText
                    <p>
                        <a class="btn btn-primary btn-xs js-see-answ" data-id="@elm.Id">Ver respuestas</a>
                    </p>
                </div>
            }

        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <button class="btn btn-success js-save">Guardar</button>
    </div>
</div>

@section Scripts{
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            var service = abp.services.app.survey;
            
            $("#listOne, #listTwo").sortable({
                connectWith: ".connectedSortable"
            }).disableSelection();

            $(".js-save").click(function () {
                var elms = $("#listTwo").find(".js-question");
                console.log(elms);
                var arr = [];
                for (var i = 0; i < elms.length; i++) {
                    var $elm = $(elms[i]);
                    var id = $elm.data("id");
                    var sId = $elm.data("s");

                    arr.push({
                        surveyId: sId,
                        questionId: id
                    });
                }
                console.log(arr);
                service.assignQuestionsToSurvey(arr, $("#SurveyId").val()).done(function() {
                    abp.message.success("¡Cambios guardados con exito!");
                });
            });

        });
    </script>
}

Survey.Web/Views/SurveyAdmin/Index.cshtml
@model List<Survey.Application.SurveyService.Dto.SurveyDto>
@{
    Layout = "~/Views/Shared/_Layout_Survey.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <h2>Gestión de encuestas</h2>
        <a class="btn btn-primary" href="@Url.Action("Index","QuestionAdmin")">Gestionar preguntas</a>
        <a class="btn btn-primary" href="@Url.Action("Index","AnswersAdmin")">Gestionar respuestas</a>
        <hr/>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#SurveyCreateModal">Crear encuesta</button>
        
        <div class="form-group">
            <input type="search" class="form-control" placeholder="Buscar"/> 
        </div>

        <div class="list-group">
            @if (!Model.Any())
            {
                <h3 class="text-center">No hay encuestas</h3>
            }
            @foreach (var surveyDto in Model)
            {
                <div class="list-group-item">
                    <h3>@surveyDto.Description</h3>
                    <p>Fecha de Inicio:<strong> @surveyDto.StartDateTime.ToShortDateString()</strong></p>
                    <p>Fecha de Cierre:<strong> @surveyDto.EndDateTime.ToShortDateString()</strong></p>

                    <p>
                        <a href="@Url.Action("AddQuestions",new { id = surveyDto.Id})" class="btn btn-primary btn-xs">Asignar preguntas</a>
                        <a class="btn btn-default btn-xs">Editar</a>
                        <a class="btn btn-danger btn-xs js-delete" data-id="@surveyDto.Id">Eliminar</a>
                    </p>
                    <br/>
                    <p>
                        <button class="btn btn-default">Ver respuestas</button>
                    </p>
                </div>
            }
        </div>

    </div>
</div>



@section Scripts{
    
    <div class="modal fade" id="SurveyCreateModal" tabindex="-1" role="dialog" aria-labelledby="SurveyCreateModalLabel" data-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="surveyCreateForm" role="form" novalidate class="form-validation">
                    <div class="modal-header">
                        <h4 class="modal-title">
                            <span>@L("CreateNewSurvey")</span>
                        </h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="text" class="form-control" name="description"/>
                        </div>
                        <div class="form-group">
                            <input type="date" class="form-control" name="startDateTime" />
                        </div>
                        <div class="form-group">
                            <input type="date" class="form-control" name="endDateTime" />
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">@L("Cancel")</button>
                        <button type="submit" class="btn btn-primary blue"><i class="fa fa-save"></i> <span>@L("Save")</span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="~/Views/SurveyAdmin/Index.js"></script>
    
}